# This compose file generates the fms service with the proper environment variables for use with nginx-proxy
# See: https://github.com/nginx-proxy/nginx-proxy

# The other services use fms-<service> as their name, for use with monorepos without name collisions

services:
  fms-prep: 
    extends:
      file: compose.yml
      service: prep

  fms:
    extends: 
      file: compose.yml
      service: fms
    environment:
      VIRTUAL_HOST: $DOMAIN
      VIRTUAL_PORT: 443
      CERT_NAME: ${CERT_NAME:-$DOMAIN}
      VIRTUAL_PROTO: https

  fms-backup:
    extends:
      file: compose.yml
      service: backup
  fms-restore:
    extends:
      file: compose.yml
      service: restore

volumes:
  fms:
    name: ${FMS_VOL:-fms}
  devin:
    name: ${DEVIN_VOL:-devin}