# prep
include:
  - path: compose.prep.yml              # Image creation
  - path: compose.bu.yml                # Backup/restore volumes to/from tarballs
  - path: scripts/migration/compose.yml # FMDataMigration tool

services:
  fms:          # FileMaker Server
    profiles:
      - live
    image: ${IMAGE:-fms}:$TAG_PREFIX${TAG_PREFIX:+-}$VERSION-u$UBUNTU-${PROCESSOR:-amd}${TAG_SUFFIX:+-}$TAG_SUFFIX
    container_name: fms
    hostname: fms
    privileged: true
    stop_grace_period: 0s
    ports:
      # - 80:80
      # - 443:443
      # - 2399:2399
      - 5003:5003
      # - 16001:16001
    volumes:
      # Volumes
      - fms:/opt/FileMaker/FileMaker Server
      - devin:/opt/Devin
      # Mounts
      - ${FILES_MOUNT:-./mounts/files}:/opt/FileMaker/FileMaker Server/Data/Databases/RC_Data_FMS:rw
      - ${BACKUPS_MOUNT:-./mounts/backups}:/opt/FileMaker/FileMaker Server/Data/Backups:rw
      - ${CLONES_MOUNT:-./mounts/clones}:/opt/FileMaker/FileMaker Server/Data/ClonesOnly:rw
      # Sync time with host
      - /etc/localtime:/etc/localtime:ro

volumes:
  fms:
    name: ${FMS_VOL:-fms}
  devin:
    name: ${DEVIN_VOL:-devin}