services:
  fms-prep: 
    extends:
      file: compose.yml
      service: prep

  fms:
    extends: 
      file: compose.yml
      service: fms
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 443
      CERT_NAME: ${CERT_NAME:-${DOMAIN}}
      test:
      test2: tt
