services:
  prep-base:
    profiles: [nothing]         # Made so that this never composes by default, unless specifically called for (Which wouldn't work anyway)
    container_name: fms-prep
    hostname: fms-prep
    privileged: true
    stop_grace_period: 0s
    volumes: 
      - ./prep/installations:/install
    ports: 
      - 10443:443

  prep: 
    profiles: [prep]
    extends:
      service: prep-base
    build:
      context: ./prep/dockerfiles
      dockerfile: dockerfile.u${UBUNTU:?}.${PROCESSOR:-amd}
    image: deanayalon/fms-prep:u$UBUNTU-${PROCESSOR:-amd}

  modify:
    extends: 
      service: prep-base
    image: ${IMAGE:-fms}:$TAG_PREFIX${TAG_PREFIX:+-}$VERSION-u$UBUNTU-${PROCESSOR:-amd}${TAG_SUFFIX:+-}$TAG_SUFFIX