services:
  prep-base:
    profiles: [nothing]         # Made so that this never composes by default, unless specifically called for (Which wouldn't work anyway)
    container_name: fms-prep
    hostname: fms-prep
    privileged: true
    stop_grace_period: 0s
    volumes: 
      - ./installations:/install
    ports: 
      - 10443:443

  prep: 
    profiles: [prep]
    extends:
      service: prep-base
    image: deanayalon/fms-prep:u$UBUNTU
    build:
      context: ./dockerfiles
      dockerfile: dockerfile.u${UBUNTU:?}
      platforms:
        - linux/amd64
        - linux/arm64

  mod:
    extends: 
      service: prep-base
    image: ${IMAGE:-fms}:$TAG_PREFIX${TAG_PREFIX:+-}$VERSION-u$UBUNTU${TAG_SUFFIX:+-}$TAG_SUFFIX