# To use this by default, add this line to .env: COMPOSE_FILE=compose.standalone.yml:compose.yml

services:
  fms:
    extends:
      file: compose.yml
      service: fms
    ports:
      - ${FMS_PORT:-443}:443

volumes:
  fms:
    name: ${FMS_VOL:-fms}
  devin:
    name: ${DEVIN_VOL:-devin}