version: '3.8'
services:
  fms-docker:
    image: jackdeaniels/private:fms-19.6.4
    container_name: fms-docker
    hostname: fms-docker
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "2399:2399"
      - "5003:5003"
    volumes:
      - ../data:/opt/FileMaker/FileMaker Server/Data